//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2024 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2024.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 199
        ///227
        ///229
        ///230
        ///233
        ///228
        ///231
        ///226
        ///237
        ///259
        ///262
        ///265
        ///266
        ///265
        ///269
        ///276
        ///278
        ///279
        ///281
        ///287
        ///305
        ///316
        ///314
        ///320
        ///313
        ///314
        ///315
        ///329
        ///346
        ///357
        ///370
        ///369
        ///360
        ///384
        ///383
        ///401
        ///402
        ///403
        ///404
        ///403
        ///406
        ///408
        ///406
        ///401
        ///393
        ///395
        ///416
        ///418
        ///408
        ///411
        ///412
        ///416
        ///417
        ///404
        ///421
        ///436
        ///437
        ///436
        ///420
        ///388
        ///405
        ///403
        ///371
        ///376
        ///378
        ///374
        ///378
        ///377
        ///403
        ///411
        ///444
        ///424
        ///417
        ///416
        ///419
        ///436
        ///415
        ///413
        ///429
        ///446
        ///462
        ///463
        ///464
        ///467
        ///466
        ///475
        ///483
        ///478
        ///487
        ///488
        ///469
        ///470
        ///472
        ///473
        ///460
        ///463
        ///465
        ///477
        ///487
        ///508
        ///506
        ///509
        ///51 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2021_Day01 {
            get {
                return ResourceManager.GetString("_2021_Day01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 58692   56129
        ///45806   95015
        ///61519   31093
        ///77848   16487
        ///98705   66749
        ///40109   81197
        ///26355   75702
        ///68715   92381
        ///56304   23460
        ///37264   12036
        ///43236   27331
        ///43577   28168
        ///77477   20638
        ///53092   44012
        ///37180   48396
        ///20616   32705
        ///97334   49126
        ///73040   28694
        ///21873   15026
        ///84281   40798
        ///42579   91319
        ///58950   66300
        ///41645   92178
        ///94750   65101
        ///32915   60179
        ///44562   71858
        ///93775   59687
        ///19512   81598
        ///99696   83818
        ///21597   11382
        ///56743   16557
        ///78901   99638
        ///41593   96712
        ///32215   53944
        ///44 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2024_Day01 {
            get {
                return ResourceManager.GetString("_2024_Day01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3   4
        ///4   3
        ///2   5
        ///1   3
        ///3   9
        ///3   3.
        /// </summary>
        internal static string _2024_Day01_Example {
            get {
                return ResourceManager.GetString("_2024_Day01_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18 21 22 24 26 29 28
        ///9 11 14 17 18 21 21
        ///48 51 54 56 60
        ///6 8 10 11 16
        ///75 76 79 82 80 83
        ///28 31 33 32 33 30
        ///94 96 94 96 96
        ///42 44 45 44 46 50
        ///25 28 29 26 33
        ///37 39 39 42 43
        ///49 51 53 56 56 57 55
        ///88 91 91 93 96 99 99
        ///56 59 59 61 62 65 68 72
        ///30 33 35 37 39 42 42 49
        ///14 17 19 23 24
        ///2 4 5 9 12 15 16 14
        ///88 89 93 96 99 99
        ///68 70 71 74 78 81 85
        ///46 47 49 53 58
        ///36 39 41 47 49 50 51 54
        ///81 82 85 91 93 95 96 94
        ///11 14 16 18 23 23
        ///72 75 81 84 85 89
        ///40 41 44 46 51 53 58
        ///70 68 71 73 76 77 78 80
        ///83 80 83 86 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2024_Day02 {
            get {
                return ResourceManager.GetString("_2024_Day02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 6 4 2 1
        ///1 2 7 8 9
        ///9 7 6 2 1
        ///1 3 2 4 5
        ///8 6 4 4 1
        ///1 3 6 7 9.
        /// </summary>
        internal static string _2024_Day02_Example {
            get {
                return ResourceManager.GetString("_2024_Day02_Example", resourceCulture);
            }
        }
    }
}
